apiVersion: v1
kind: Service
metadata:
  name: boop-service
  labels:
    app: boop-app
spec:
  selector:
    app: boop-app
  ports:
    - name: boop-http-service
      protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30000
