FROM node:14.18.1-alpine

RUN mkdir -p /home/boop
WORKDIR /home/boop

COPY client/package.json client/
COPY server/package.json server/

RUN cd server && npm install --production
RUN cd client && npm install --production

ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG FACEBOOK_CLIENT_SECRET
ARG FACEBOOK_CLIENT_ID
ARG TOKEN_SECRET

ENV GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
ENV GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
ENV FACEBOOK_CLIENT_SECRET=$FACEBOOK_CLIENT_SECRET
ENV FACEBOOK_CLIENT_ID=$FACEBOOK_CLIENT_ID
ENV TOKEN_SECRET=$TOKEN_SECRET
ENV NODE_ENV=production
ENV PORT=5000

COPY server/ server/
COPY client/ client/
RUN cd client && npm run build

EXPOSE 5000
CMD ["node", "server/bin/www"]