version: '3.1'
services:
  db:
    image: 'postgres'
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USERNAME
    networks:
      - boop
    volumes:
      - ./data:/var/lib/postgresql/data
  app:
    networks:
      - boop
    image: 'boop:0.1.0'
    restart: unless-stopped
    ports:
      - 8080:5000
    environment:
      GOOGLE_CLIENT_ID: $GOOGLE_CLIENT_ID
      GOOGLE_CLIENT_SECRET: $GOOGLE_CLIENT_SECRET
      FACEBOOK_CLIENT_ID: $FACEBOOK_CLIENT_ID
      FACEBOOK_CLIENT_SECRET: $FACEBOOK_CLIENT_SECRET
      TOKEN_SECRET: $TOKEN_SECRET
    depends_on:
      - db

networks:
  boop: