version: '3.1'
services:
  boop_db:
    image: 'postgres'
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USERNAME
    volumes:
      - ./data:/var/lib/postgresql/data