name: ESlint

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install modules
        run: npm ci && npm ci --prefix client && npm ci --prefix server

      - name: Run ESLint
        run: npm run lint
